import { createClient } from '@/lib/supabase/server'
import { FileText } from 'lucide-react'
import { ReportsPageClient } from '@/components/reports/ReportsPageClient'

export default async function ReportsPage() {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  const { data: reports } = await supabase
    .from('reports')
    .select('*')
    .eq('user_id', user!.id)
    .order('created_at', { ascending: false })

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white flex items-center gap-2">
          <FileText className="w-6 h-6 text-cyan-400" />
          Reports
        </h1>
        <p className="text-slate-400 mt-1">
          Weekly executive summaries generated by your AI Chief of Staff.
        </p>
      </div>

      <ReportsPageClient initialReports={reports || []} />
    </div>
  )
}